### PR TITLE
fix concurrency issue in notifyWritePositions

### LINKED ISSUE #495: Inconsistent writes
When writing events to Axon Server sometimes events are written that are then available in the complete event stream, but not in an aggregate-specific event stream. The issue does not occur while using Enterprise edition.

Someone has supplied us with a Docker container, specifically designed to cause this issue. It can do so quite reliably. In order to run it, run the following:

`docker run --rm -e AxonServer__Endpoint=http://192.168.50.185:8124 robindv/axonserver-tester:latest`

Replace the endpoint with your external IP, since it is docker. 

What happens is that the events were written:
image

However, for the specific aggregate the events are not there:
image

After a restart, the events are present.

### PR DESCRIPTION
**Pull request by MGathier**
fixes #495 

The iterator used to check the writePositions is only weakly consistent and may not see new entries in the underlying map.
If two writes call this operation in parallel, they should each check all completed write positions (only one of them will do the work).

### CODE REVIEW

File: axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/Synchronizer.java [hunk 1]
```diff
@@ -61,25 +64,26 @@ public Synchronizer(EventTypeContext context, StorageProperties storagePropertie
...
-                        } else {
-                            break;
-                        }
+            for (Iterator<Map.Entry<WritePosition, StorageCallback>> iterator = writePositions
+                    .entrySet().iterator(); iterator.hasNext(); ) {
+                Map.Entry<WritePosition, StorageCallback> writePositionEntry = iterator
+                        .next();
+
+                WritePosition writePosition = writePositionEntry.getKey();
+                if (!writePosition.isComplete()) {
```
Comment (m1l4n54v1c) [inline axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/Synchronizer.java:73]: Could you elaborate on how this fixes the concurrency issue? :)

File: axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/PrimaryEventStore.java [hunk 2]
```diff
@@ -423,7 +423,7 @@ private WritePosition claim(int eventBlockSize, int nrOfEvents) {
         do {
             writePosition = writePositionRef.getAndAccumulate(
                     new WritePosition(nrOfEvents, totalSize),
```
Comment (saratry) [inline axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/PrimaryEventStore.java:425]: maybe it makes more sense to do something like:
`writePosition = writePositionRef.getAndUpdate(prev -> prev.incrementedWith(nrOfEvents, totalSize));`

File: axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/WritePosition.java [hunk 3]
```diff
@@ -12,35 +12,53 @@
...
                       .thenComparingInt(WritePosition::getPosition);
     final long sequence;
     final int position;
     final WritableEventSource buffer;
     final Long segment;
+    public int prevEntries;
 
-    public WritePosition(long sequence, int position) {
-        this(sequence, position, null, null);
+    public WritePosition(long prevEntries, int position) {
```
Comment (saratry) [inline axonserver/src/main/java/io/axoniq/axonserver/localstorage/file/WritePosition.java:31]: This constructor allows the creation of an inconsistent WritePosition and should be deleted.

**Review by saratry — APPROVED** [review]

**Review by m1l4n54v1c — APPROVED** [review]
